UPDATE `quest_template_addon` SET `PrevQuestID` = '12720', `ExclusiveGroup` = '-12716' WHERE (`ID` = '12723');
UPDATE `gossip_menu_option` SET `OptionType` = '3' WHERE (`MenuId` = '9755') and (`OptionIndex` = '0');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12751' WHERE (`ID` = '12754');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12723' WHERE (`ID` = '12725');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12739');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12742');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12743');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12744');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12745');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12746');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12747');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12748');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12749');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12750');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '28649');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '28650');
UPDATE `quest_template` SET `AllowableRaces` = '1' WHERE (`ID` = '12742');
UPDATE `quest_template` SET `AllowableRaces` = '8' WHERE (`ID` = '12743');
UPDATE `quest_template` SET `AllowableRaces` = '4' WHERE (`ID` = '12744');
UPDATE `quest_template` SET `AllowableRaces` = '512' WHERE (`ID` = '12747');
UPDATE `quest_template` SET `AllowableRaces` = '128' WHERE (`ID` = '12749');
UPDATE `quest_template` SET `AllowableRaces` = '2097152' WHERE (`ID` = '28649');
UPDATE `creature_queststarter` SET `id` = '29110' WHERE (`id` = '25462') and (`quest` = '12779');
UPDATE `creature_questender` SET `id` = '29110' WHERE (`id` = '25462') and (`quest` = '12779');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12800' WHERE (`ID` = '12801');
DELETE FROM `gossip_menu_option` WHERE (`MenuId` = '10027') and (`OptionIndex` = '1');
DELETE FROM `gossip_menu_option` WHERE (`MenuId` = '10027') and (`OptionIndex` = '2');
UPDATE `gossip_menu_option` SET `OptionType` = '3' WHERE (`MenuId` = '12759') and (`OptionIndex` = '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('10400', '0', '0', '0', '10395', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('10079', '0', '0', '0', '10142', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('14', '7865', '9632', '0', '0', '8', '0', '10099', '0', '0', '0', '0', '0', '', '');
INSERT INTO `gossip_menu_option_action` (`MenuId`, `OptionIndex`, `ActionMenuId`, `ActionPoiId`) 
SELECT menuid, 2, 10371, 0 FROM gossip_menu_option where optiontype = 20 and optionindex = 2 and menuid not in (SELECT menuid FROM gossip_menu_option_action where actionmenuid = 10371);
UPDATE `quest_template_addon` SET `PrevQuestID` = '10144' WHERE (`ID` = '10146');
DELETE FROM `gossip_menu_option` WHERE (`MenuId` = '7970') and (`OptionIndex` = '2');
DELETE FROM `gossip_menu_option` WHERE (`MenuId` = '7970') and (`OptionIndex` = '3');
UPDATE `conditions` SET `NegativeCondition` = '0' WHERE (`SourceTypeOrReferenceId` = '15') and (`SourceGroup` = '7970') and (`SourceEntry` = '1') and (`SourceId` = '0') and (`ElseGroup` = '0') and (`ConditionTypeOrReference` = '8') and (`ConditionTarget` = '0') and (`ConditionValue1` = '10340') and (`ConditionValue2` = '0') and (`ConditionValue3` = '0');
UPDATE `conditions` SET `ConditionValue1` = '10146' WHERE (`SourceTypeOrReferenceId` = '15') and (`SourceGroup` = '7970') and (`SourceEntry` = '1') and (`SourceId` = '0') and (`ElseGroup` = '0') and (`ConditionTypeOrReference` = '8') and (`ConditionTarget` = '0') and (`ConditionValue1` = '10340') and (`ConditionValue2` = '0') and (`ConditionValue3` = '0');
UPDATE `smart_scripts` SET `target_type` = '2' WHERE (`entryorguid` = '19424') and (`source_type` = '0') and (`id` = '0') and (`link` = '0');
UPDATE `mail_level_reward` SET `level` = '70' WHERE (`level` = '60') and (`raceMask` = '690');
UPDATE `mail_level_reward` SET `level` = '70' WHERE (`level` = '60') and (`raceMask` = '1101');
UPDATE `trainer_spell` SET `ReqLevel` = '70' WHERE (`TrainerId` = '39') and (`SpellId` = '33950');
UPDATE `trainer_spell` SET `ReqLevel` = '70' WHERE (`TrainerId` = '386') and (`SpellId` = '34092');
UPDATE `trainer_spell` SET `ReqLevel` = '70' WHERE (`TrainerId` = '137') and (`SpellId` = '34092');
UPDATE `trainer_spell` SET `ReqLevel` = '85' WHERE (`TrainerId` = '386') and (`SpellId` = '90269');
UPDATE `trainer_spell` SET `ReqLevel` = '85' WHERE (`TrainerId` = '137') and (`SpellId` = '90269');
UPDATE `trainer_spell` SET `ReqLevel` = '80' WHERE (`TrainerId` = '386') and (`SpellId` = '54198');
UPDATE `trainer_spell` SET `ReqLevel` = '80' WHERE (`TrainerId` = '137') and (`SpellId` = '54198');
UPDATE `trainer_spell` SET `ReqLevel` = '70' WHERE (`TrainerId` = '386') and (`SpellId` = '90266');
UPDATE `trainer_spell` SET `ReqLevel` = '70' WHERE (`TrainerId` = '137') and (`SpellId` = '90266');
UPDATE `smart_scripts` SET `event_flags` = '1' WHERE (`entryorguid` = '19440') and (`source_type` = '0') and (`id` = '0') and (`link` = '0');
UPDATE `smart_scripts` SET `event_flags` = '0' WHERE (`entryorguid` = '19440') and (`source_type` = '0') and (`id` = '1') and (`link` = '0');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('19440', '0', '2', '0', '0', '0', '100', '0', '1000', '1500', '0', '0', '0', '11', '40861', '0', '0', '0', '0', '0', '2', '0', '0', '0', '0', '0', '0', '0', 'lfm - Eye of Grillok - Wicked Beam');
UPDATE `trainer_spell` SET `MoneyCost` = '400000' WHERE (`TrainerId` = '386') and (`SpellId` = '33389');
UPDATE `trainer_spell` SET `MoneyCost` = '400000' WHERE (`TrainerId` = '137') and (`SpellId` = '33389');
UPDATE `trainer_spell` SET `MoneyCost` = '400000' WHERE (`TrainerId` = '46') and (`SpellId` = '33389');
UPDATE `trainer_spell` SET `MoneyCost` = '5000000' WHERE (`TrainerId` = '386') and (`SpellId` = '33392');
UPDATE `trainer_spell` SET `MoneyCost` = '5000000' WHERE (`TrainerId` = '137') and (`SpellId` = '33392');
UPDATE `trainer_spell` SET `MoneyCost` = '5000000' WHERE (`TrainerId` = '46') and (`SpellId` = '33392');
UPDATE `trainer_spell` SET `MoneyCost` = '50000000', `ReqLevel` = '60' WHERE (`TrainerId` = '39') and (`SpellId` = '33950');
UPDATE `trainer_spell` SET `MoneyCost` = '50000000', `ReqLevel` = '60' WHERE (`TrainerId` = '386') and (`SpellId` = '34092');
UPDATE `trainer_spell` SET `MoneyCost` = '50000000', `ReqLevel` = '60' WHERE (`TrainerId` = '137') and (`SpellId` = '34092');
UPDATE `trainer_spell` SET `MoneyCost` = '100000000', `ReqLevel` = '70' WHERE (`TrainerId` = '386') and (`SpellId` = '34093');
UPDATE `trainer_spell` SET `MoneyCost` = '100000000', `ReqLevel` = '70' WHERE (`TrainerId` = '137') and (`SpellId` = '34093');
UPDATE `trainer_spell` SET `MoneyCost` = '150000000', `ReqLevel` = '80' WHERE (`TrainerId` = '386') and (`SpellId` = '90266');
UPDATE `trainer_spell` SET `MoneyCost` = '150000000', `ReqLevel` = '80' WHERE (`TrainerId` = '137') and (`SpellId` = '90266');
UPDATE `trainer_spell` SET `MoneyCost` = '100000000', `ReqLevel` = '68' WHERE (`TrainerId` = '386') and (`SpellId` = '54198');
UPDATE `trainer_spell` SET `MoneyCost` = '100000000', `ReqLevel` = '68' WHERE (`TrainerId` = '137') and (`SpellId` = '54198');
UPDATE `trainer_spell` SET `MoneyCost` = '150000000', `ReqLevel` = '60' WHERE (`TrainerId` = '386') and (`SpellId` = '90269');
UPDATE `trainer_spell` SET `MoneyCost` = '150000000', `ReqLevel` = '60' WHERE (`TrainerId` = '137') and (`SpellId` = '90269');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '16');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '128');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '32');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '2');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '8');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '1');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '64');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '4');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '1024');
UPDATE `mail_level_reward` SET `level` = '90' WHERE (`level` = '20') and (`raceMask` = '512');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '512');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '1024');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '4');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '64');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '1');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '8');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '2');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '32');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '128');
UPDATE `mail_level_reward` SET `level` = '91' WHERE (`level` = '40') and (`raceMask` = '16');
UPDATE `mail_level_reward` SET `level` = '92' WHERE (`level` = '60') and (`raceMask` = '690');
UPDATE `mail_level_reward` SET `level` = '92' WHERE (`level` = '60') and (`raceMask` = '1101');
UPDATE `mail_level_reward` SET `level` = '93' WHERE (`level` = '70') and (`raceMask` = '690');
UPDATE `mail_level_reward` SET `level` = '93' WHERE (`level` = '70') and (`raceMask` = '1101');
UPDATE `smart_scripts` SET `action_param1` = '39415' WHERE (`entryorguid` = '19424') and (`source_type` = '0') and (`id` = '0') and (`link` = '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('10382', '0', '0', '0', '10163', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
insert into gameobject 
select guid, id, map, zoneid, areaid, spawnmask, 0, phasemask, 169, 0, -1, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state, scriptname, verifiedbuild 
from gameobject where id = 183123;
UPDATE `gameobject_template` SET `displayId` = '0' WHERE (`entry` = '183123');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('9543', '0', '0', '0', '9424', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
UPDATE `creature_model_info` SET `CombatReach` = '5' WHERE (`DisplayID` = '20746');
UPDATE `smart_scripts` SET `action_param1` = '30093' WHERE (`entryorguid` = '16977') and (`source_type` = '0') and (`id` = '12') and (`link` = '0');
UPDATE `creature_template` SET `npcflag` = '83' WHERE (`entry` = '21209');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('9385', '0', '0', '0', '9558', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('9563', '0', '0', '0', '9558', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
UPDATE `smart_scripts` SET `action_type` = '41' WHERE (`entryorguid` = '181582') and (`source_type` = '1') and (`id` = '1') and (`link` = '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('10132', '0', '0', '0', '10443', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('10159', '0', '0', '0', '10443', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('9912', '0', '0', '0', '10443', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('1740400', '9', '7', '0', '0', '0', '100', '0', '9000', '9000', '0', '0', '0', '37', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Vindicator Sedai - Die');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('17000', '0', '0', '0', '0', '0', '100', '0', '2000', '4000', '10000', '15000', '0', '11', '21068', '32', '0', '0', '0', '0', '2', '0', '0', '0', '0', '0', '0', '0', 'corruption');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('17000', '0', '1', '0', '0', '0', '100', '0', '8000', '12000', '10000', '15000', '0', '11', '22678', '0', '0', '0', '0', '0', '2', '0', '0', '0', '0', '0', '0', '0', 'fear');
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE (`entry` = '17000');
UPDATE `smart_scripts` SET `event_flags` = '513' WHERE (`entryorguid` = '7385') and (`source_type` = '0') and (`id` = '1') and (`link` = '0');
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseUseFlags`, `phaseMask`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES ('215419', '54603', '543', '3562', '3562', '3', '0', '1', '169', '0', '-1', '0', '0', '-1343.26', '1650.59', '68.9473', '0.6687', '300', '0', '0', '1', '0', '0', '0', '898', '0', '', '0');
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseUseFlags`, `phaseMask`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES ('226493', '54629', '542', '3713', '3713', '3', '0', '1', '169', '0', '-1', '0', '0', '-0.834323', '-6.44807', '-43.1633', '4.83269', '300', '0', '0', '1', '0', '0', '0', '898', '0', '', '0');
DELETE FROM `creature_loot_template` WHERE (`Entry` = '17537') and (`Item` = '23892');
DELETE FROM `creature_loot_template` WHERE (`Entry` = '17537') and (`Item` = '23890');
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = '1') and (`SourceGroup` = '17537') and (`SourceEntry` = '23892') and (`SourceId` = '0') and (`ElseGroup` = '0') and (`ConditionTypeOrReference` = '6') and (`ConditionTarget` = '0') and (`ConditionValue1` = '67') and (`ConditionValue2` = '0') and (`ConditionValue3` = '0');
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = '1') and (`SourceGroup` = '17537') and (`SourceEntry` = '23890') and (`SourceId` = '0') and (`ElseGroup` = '0') and (`ConditionTypeOrReference` = '6') and (`ConditionTarget` = '0') and (`ConditionValue1` = '469') and (`ConditionValue2` = '0') and (`ConditionValue3` = '0');
insert into gameobject 
select guid, id, map, zone, area, spawnmask, 0, phasemask, 169, 0, -1, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state, '', 0 
from world_emucoach.gameobject where id = 209347 or id = 209348;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('80240', 'spell_warl_bane_of_havoc');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('85466', 'spell_warl_bane_of_havoc_track');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('29539', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2');
UPDATE `areatrigger_involvedrelation` SET `quest` = '29539' WHERE (`id` = '4200');
UPDATE `creature_template` SET `unit_flags` = '0' WHERE (`entry` = '17398');
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `IsCurrency`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('17381', '73200', '0', '100', '1', '0', '1', '1', '1', '1');
UPDATE `gossip_menu_option` SET `OptionType` = '3' WHERE (`MenuId` = '7396') and (`OptionIndex` = '0');
UPDATE `gossip_menu_option` SET `OptionType` = '3' WHERE (`MenuId` = '10437') and (`OptionIndex` = '1');
UPDATE `creature_template` SET `unit_flags` = '0' WHERE (`entry` = '19733');
UPDATE `creature_template` SET `ScriptName` = 'npc_dk_ghoul' WHERE (`entry` = '26125');
UPDATE `creature` SET `spawndist` = '3', `MovementType` = '1' WHERE (`guid` = '64859');
UPDATE `creature` SET `spawndist` = '3', `MovementType` = '1' WHERE (`guid` = '64860');
UPDATE `creature` SET `spawndist` = '3', `MovementType` = '1' WHERE (`guid` = '64861');
UPDATE `creature` SET `spawndist` = '3', `MovementType` = '1' WHERE (`guid` = '64862');
UPDATE `creature` SET `spawndist` = '3', `MovementType` = '1' WHERE (`guid` = '64863');
UPDATE `creature` SET `spawndist` = '3', `MovementType` = '1' WHERE (`guid` = '64864');
update creature set spawndist = 3, movementtype = 1 where id = 18912 and movementtype = 0;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES ('31746', '31773', '0', 'Whisper Aura 0');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES ('-31773', '31774', '0', 'Whisper Aura 1');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES ('-31774', '31775', '0', 'Whisper Aura 2');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES ('-31775', '31776', '0', 'Whisper Aura 3');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES ('-31776', '31777', '0', 'Whisper Aura 4');
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES ('11286', '0', '0', '4', '0', '0', '0', '0', '0', '0');
UPDATE `event_scripts` SET `dataint` = '14706' WHERE (`entry` = '464');
UPDATE `event_scripts` SET `command` = '10', `datalong` = '17841', `datalong2` = '100', `dataint` = '0' WHERE (`entry` = '464');
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES ('11289', '0', '10', '17841', '100', '0', '0', '0', '0', '0');
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES ('11290', '0', '10', '17841', '100', '0', '0', '0', '0', '0');
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES ('11291', '0', '10', '17841', '100', '0', '0', '0', '0', '0');
delete from creature_text where creatureid = 17841;
insert into creature_text 
select creatureid, groupid, id, text, type, language, probability, emote, duration, sound, 0, broadcasttextid, textrange, comment 
from world_trinitycore_wlk.creature_text where creatureid = 17841;
UPDATE `smart_scripts` SET `comment` = 'Ysiel Windsinger - Just summoned - invisible' WHERE (`entryorguid` = '17841') and (`source_type` = '0') and (`id` = '1') and (`link` = '0');
UPDATE `smart_scripts` SET `event_type` = '38', `event_param1` = '1', `event_param2` = '1', `comment` = 'Ysiel Windsinger - Just summoned - Say tex 0' WHERE (`entryorguid` = '17841') and (`source_type` = '0') and (`id` = '2') and (`link` = '0');
UPDATE `smart_scripts` SET `event_type` = '38', `event_param1` = '1', `event_param2` = '2', `comment` = 'Ysiel Windsinger - Just summoned - Say tex 1' WHERE (`entryorguid` = '17841') and (`source_type` = '0') and (`id` = '3') and (`link` = '0');
UPDATE `smart_scripts` SET `event_type` = '38', `event_param1` = '1', `event_param2` = '3', `comment` = 'Ysiel Windsinger - Just summoned - Say tex 2' WHERE (`entryorguid` = '17841') and (`source_type` = '0') and (`id` = '4') and (`link` = '0');
UPDATE `smart_scripts` SET `event_type` = '38', `event_param1` = '1', `event_param2` = '4', `comment` = 'Ysiel Windsinger - Just summoned - Say tex 3' WHERE (`entryorguid` = '17841') and (`source_type` = '0') and (`id` = '5') and (`link` = '0');
UPDATE `event_scripts` SET `dataint` = '1' WHERE (`entry` = '464');
UPDATE `event_scripts` SET `dataint` = '2' WHERE (`entry` = '465');
UPDATE `event_scripts` SET `dataint` = '3' WHERE (`entry` = '466');
UPDATE `event_scripts` SET `dataint` = '4' WHERE (`entry` = '467');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('18214', '0', '0', '0', '0', '0', '100', '0', '3000', '5000', '10000', '15000', '0', '11', '6016', '0', '0', '0', '0', '0', '2', '0', '0', '0', '0', '0', '0', '0', 'Fenclaw Thrasher - IC - Cast \'Pierce Armor\'');
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE (`entry` = '18214');
UPDATE `gossip_menu_option` SET `OptionIcon` = '0', `OptionBroadcastTextId` = '10693' WHERE (`MenuId` = '7481') and (`OptionIndex` = '0');
UPDATE `gossip_menu_option` SET `OptionIcon` = '5', `OptionText` = 'Make this inn your home.', `OptionBroadcastTextId` = '2822' WHERE (`MenuId` = '7481') and (`OptionIndex` = '1');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('14', '7574', '9204', '0', '0', '8', '0', '9743', '0', '0', '0', '0', '0', '', '');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('14', '7574', '9204', '0', '0', '8', '0', '9739', '0', '0', '0', '0', '0', '', '');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('14', '7574', '9204', '0', '0', '5', '0', '970', '248', '0', '0', '0', '0', '', '');
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseUseFlags`, `phaseMask`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES ('215090', '54674', '546', '3716', '3716', '1', '0', '31', '169', '0', '-1', '0', '0', '31.4086', '-32.1966', '-2.74908', '5.777', '604800', '0', '0', '1', '0', '0', '0', '0', '0', '', '0');
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseUseFlags`, `phaseMask`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES ('500864', '54667', '547', '3717', '3717', '1', '0', '1', '169', '0', '-1', '0', '0', '135.137', '-114.338', '-1.59057', '3.79424', '604800', '0', '0', '1', '0', '0', '0', '0', '0', '', '0');
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseUseFlags`, `phaseMask`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES ('215088', '54675', '546', '3716', '3716', '1', '0', '31', '169', '0', '-1', '0', '0', '33.3729', '-25.4775', '-2.75236', '5.52369', '604800', '0', '0', '1', '0', '0', '0', '0', '0', '', '0');
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseUseFlags`, `phaseMask`, `PhaseId`, `PhaseGroup`, `terrainSwapMap`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES ('215200', '54848', '545', '3715', '3715', '1', '0', '31', '169', '0', '-1', '0', '0', '-0.948525', '-15.462633', '-4.962857', '4.743805', '604800', '0', '0', '1', '0', '0', '0', '0', '0', '', '0');
DELETE FROM `creature` WHERE (`id` = '17884');
UPDATE `creature_template` SET `unit_flags` = '768' WHERE (`entry` = '17885');
UPDATE `conditions` SET `ConditionValue1` = '29563', `Comment` = 'Gossip option 0 requires quest 29563 active' WHERE (`SourceTypeOrReferenceId` = '15') and (`SourceGroup` = '7520') and (`SourceEntry` = '0') and (`SourceId` = '0') and (`ElseGroup` = '0') and (`ConditionTypeOrReference` = '9') and (`ConditionTarget` = '0') and (`ConditionValue1` = '9738') and (`ConditionValue2` = '0') and (`ConditionValue3` = '0');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '7540', '0', '0', '0', '1', '0', '34906', '0', '0', '1', '0', '0', '', 'Gossip option menu shows only when player does not have spell 34906');
delete from world_trinitycore_ctm.smart_scripts where entryorguid like '17893%';
insert into world_trinitycore_ctm.smart_scripts 
select entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1,  event_param2,  event_param3,  event_param4,  event_param5, 
action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, 
target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment from world_trinitycore_wlk.smart_scripts where entryorguid like '17893%';
UPDATE `creature_template` SET `gossip_menu_id` = '7520' WHERE (`entry` = '17893');

