UPDATE `quest_template_addon` SET `PrevQuestID` = '12720', `ExclusiveGroup` = '-12716' WHERE (`ID` = '12723');
UPDATE `gossip_menu_option` SET `OptionType` = '3' WHERE (`MenuId` = '9755') and (`OptionIndex` = '0');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12751' WHERE (`ID` = '12754');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12723' WHERE (`ID` = '12725');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12739');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12742');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12743');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12744');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12745');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12746');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12747');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12748');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12749');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '12750');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '28649');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12738' WHERE (`ID` = '28650');
UPDATE `quest_template` SET `AllowableRaces` = '1' WHERE (`ID` = '12742');
UPDATE `quest_template` SET `AllowableRaces` = '8' WHERE (`ID` = '12743');
UPDATE `quest_template` SET `AllowableRaces` = '4' WHERE (`ID` = '12744');
UPDATE `quest_template` SET `AllowableRaces` = '512' WHERE (`ID` = '12747');
UPDATE `quest_template` SET `AllowableRaces` = '128' WHERE (`ID` = '12749');
UPDATE `quest_template` SET `AllowableRaces` = '2097152' WHERE (`ID` = '28649');
UPDATE `creature_queststarter` SET `id` = '29110' WHERE (`id` = '25462') and (`quest` = '12779');
UPDATE `creature_questender` SET `id` = '29110' WHERE (`id` = '25462') and (`quest` = '12779');
UPDATE `quest_template_addon` SET `PrevQuestID` = '12800' WHERE (`ID` = '12801');
DELETE FROM `gossip_menu_option` WHERE (`MenuId` = '10027') and (`OptionIndex` = '1');
DELETE FROM `gossip_menu_option` WHERE (`MenuId` = '10027') and (`OptionIndex` = '2');
UPDATE `gossip_menu_option` SET `OptionType` = '3' WHERE (`MenuId` = '12759') and (`OptionIndex` = '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('10400', '0', '0', '0', '10395', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES ('10079', '0', '0', '0', '10142', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('14', '7865', '9632', '0', '0', '8', '0', '10099', '0', '0', '0', '0', '0', '', '');
INSERT INTO `gossip_menu_option_action` (`MenuId`, `OptionIndex`, `ActionMenuId`, `ActionPoiId`) 
SELECT menuid, 2, 10371, 0 FROM gossip_menu_option where optiontype = 20 and optionindex = 2 and menuid not in (SELECT menuid FROM gossip_menu_option_action where actionmenuid = 10371);